// FILE_SIGNATURE は必ず8バイト
export const FILE_SIGNATURE = "ENCFILE2";
// FORMAT_VERSION は255以下
export const FORMAT_VERSION = 3;
export const KEY_EXCHANGE_ALGORITHM = "X25519";
export const KEY_DERIVATION_ALGORITHM = "HKDF";
export const HASH_ALGORITHM = "SHA256";
export const ENCRYPTION_ALGORITHM = "AES-256-GCM";
export const ALGORITHMS =
  `${KEY_EXCHANGE_ALGORITHM}-` +
  `${KEY_DERIVATION_ALGORITHM}-` +
  `${HASH_ALGORITHM}-` +
  `${ENCRYPTION_ALGORITHM}`;
export const PREAMBLE_LENGTHS = {
  FILE_SIGNATURE: 8,
  FORMAT_VERSION: 1,
  HEADER_LENGTH: 4,
} as const;
export const PREAMBLE_LAYOUT = {
  SIGNATURE_OFFSET: 0,
  VERSION_OFFSET: PREAMBLE_LENGTHS.FILE_SIGNATURE,
  HEADER_LENGTH_OFFSET:
    PREAMBLE_LENGTHS.FILE_SIGNATURE + PREAMBLE_LENGTHS.FORMAT_VERSION,
  HEADER_OFFSET:
    PREAMBLE_LENGTHS.FILE_SIGNATURE +
    PREAMBLE_LENGTHS.FORMAT_VERSION +
    PREAMBLE_LENGTHS.HEADER_LENGTH,
} as const;

export const KDF_KEY_INFO = "file-encryption-v1";

// 暗号化ファイルのMIMEタイプ
export const ENCRYPTED_FILE_MIMETYPE = "application/octet-stream";

// デフォルト 4MBチャンク
export const DEFAULT_CHUNK_SIZE = 1024 * 1024 * 4;
export const CHUNK_HEADER_LENGTHS = {
  CIPHERTEXT_LENGTH: 4,
  IV_LENGTH: 4,
};
export const CHUNK_HEADER_LAYOUT = {
  LENGTH_OFFSET: 0,
  IV_OFFSET: CHUNK_HEADER_LENGTHS.CIPHERTEXT_LENGTH,
};


export const WARNING_FILE_SIZE = 500 * 1024 * 1024;